-- MySQL Script generated by MySQL Workbench
-- Thu Nov  2 17:23:15 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema iziImoveis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema iziImoveis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `iziImoveis` DEFAULT CHARACTER SET utf8 ;
USE `iziImoveis` ;

-- -----------------------------------------------------
-- Table `iziImoveis`.`Tb_Secao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iziImoveis`.`Tb_Secao` (
  `idTb_Secao` INT NOT NULL,
  `Inicio_da_navegacao` DATETIME NULL,
  `Termino_de_navegacao` DATETIME NULL,
  `Dispositivo` VARCHAR(45) NULL,
  `Qt_paginas_visitadas` INT NULL,
  PRIMARY KEY (`idTb_Secao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iziImoveis`.`Tb_Pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iziImoveis`.`Tb_Pessoas` (
  `CPF` VARCHAR(12) NOT NULL,
  `Status` VARCHAR(45) NULL, 
  `Nome` VARCHAR(45) NULL,
  `Sobrenome` VARCHAR(45) NULL,
  `Celular` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Endereço` VARCHAR(45) NULL,
  `Genero` VARCHAR(45) NULL,
  `Estado_civil` VARCHAR(45) NULL,
  `Data_de_nascimento` DATE NULL,
  `Data_de_cadastro` VARCHAR(45) NULL,
  `Meio_de_contado` VARCHAR(45) NULL,
  `Tb_Secao_idTb_Secao` INT NOT NULL,
  PRIMARY KEY (`CPF`),
  INDEX `fk_Tb_Pessoas_Tb_Secao_idx` (`Tb_Secao_idTb_Secao` ASC) ,
  CONSTRAINT `fk_Tb_Pessoas_Tb_Secao`
    FOREIGN KEY (`Tb_Secao_idTb_Secao`)
    REFERENCES `iziImoveis`.`Tb_Secao` (`idTb_Secao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iziImoveis`.`Tb_Locatarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iziImoveis`.`Tb_Locatarios` (
  `Codigo_do_locatario` INT NOT NULL,
  `Profissao` VARCHAR(45) NULL,
  `Refencia_pessoal` VARCHAR(45) NULL,
  `Nome_do_conjuge` VARCHAR(45) NULL,
  `Numero_de_dependentes` INT NULL,
  `Tipo_de_imovel` VARCHAR(12) NULL,
  `Faixa_de_preco` FLOAT NULL,
  `Duracao_da_locacao_desejada` INT NULL,
  `Veiculo_proprio` CHAR NULL,
  `Animais_de_estimacao` CHAR NULL,
  `Veio_por_onde` VARCHAR(45) NULL,
  `Tb_Pessoas_CPF` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`Codigo_do_locatario`),
  INDEX `fk_Tb_Locatarios_Tb_Pessoas1_idx` (`Tb_Pessoas_CPF` ASC) ,
  CONSTRAINT `fk_Tb_Locatarios_Tb_Pessoas1`
    FOREIGN KEY (`Tb_Pessoas_CPF`)
    REFERENCES `iziImoveis`.`Tb_Pessoas` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iziImoveis`.`Tb_ContratoAluguel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iziImoveis`.`Tb_ContratoAluguel` (
  `idContratoAluguel` INT NOT NULL,
  `Data_de_inicio` DATETIME NULL,
  `Data_de_termino` DATETIME NULL,
  `Data_de_renovacao` DATETIME NULL,
  `Valor_do_aluguel` FLOAT NULL,
  `Historico_de_pagamento` INT NULL,
  `Termos_e_condicoes` VARCHAR(50) NULL,
  `Firma_reconhecida_em_cartorio` CHAR NULL,
  `Necessario_deposito` CHAR NULL,
  `Porcentagem_do_site` float NULL,
  `Data_de_pagamento_do_aluguel` DATE NULL,
  `Tb_Locatarios_Codigo_do_locatario` INT NOT NULL,
  PRIMARY KEY (`idContratoAluguel`),
  INDEX `fk_Tb_ContratoAluguel_Tb_Locatarios1_idx` (`Tb_Locatarios_Codigo_do_locatario` ASC) ,
  CONSTRAINT `fk_Tb_ContratoAluguel_Tb_Locatarios1`
    FOREIGN KEY (`Tb_Locatarios_Codigo_do_locatario`)
    REFERENCES `iziImoveis`.`Tb_Locatarios` (`Codigo_do_locatario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iziImoveis`.`Tb_Proprietarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iziImoveis`.`Tb_Proprietarios` (
  `idProprietarios` INT NOT NULL,
  `Data_de_termino` DATETIME NULL,
  `Endereco` VARCHAR(45) NULL,
  `Meio_para_receber` VARCHAR(45) NULL,
  `Informacoes_bancarias` VARCHAR(45) NULL,
  `Porcentagem_a_ser_paga` FLOAT NULL,
  `Informacoes_fiscais` VARCHAR(45) NULL,
  `Tb_Pessoas_CPF` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`idProprietarios`),
  INDEX `fk_Tb_Proprietarios_Tb_Pessoas1_idx` (`Tb_Pessoas_CPF` ASC) ,
  CONSTRAINT `fk_Tb_Proprietarios_Tb_Pessoas1`
    FOREIGN KEY (`Tb_Pessoas_CPF`)
    REFERENCES `iziImoveis`.`Tb_Pessoas` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iziImoveis`.`Tb_Regiao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iziImoveis`.`Tb_Regiao` (
  `idTb_Regiao` INT NOT NULL,
  `Nome_da_regiao` VARCHAR(45) NULL,
  `Codigo_postal` VARCHAR(45) NULL,
  `Descricao` VARCHAR(45) NULL,
  `Populacao` FLOAT NULL,
  `Estado` VARCHAR(45) NULL,
  PRIMARY KEY (`idTb_Regiao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iziImoveis`.`Tb_Loja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iziImoveis`.`Tb_Loja` (
  `idLoja` INT NOT NULL,
  `Endereco` VARCHAR(45) NULL,
  `Estado` VARCHAR(45) NULL,
  `Bairro` VARCHAR(45) NULL,
  PRIMARY KEY (`idLoja`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iziImoveis`.`Tb_Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iziImoveis`.`Tb_Funcionario` (
  `idFuncionario` INT NOT NULL,
  `Data_de_inicio` DATETIME NULL,
  `Horarios` VARCHAR(45) NULL,
  `Beneficios` VARCHAR(45) NULL,
  `Salario` VARCHAR(45) NULL,
  `Tb_Pessoas_CPF` VARCHAR(12) NOT NULL,
  `Tb_Loja_idLoja` INT NOT NULL,
  PRIMARY KEY (`idFuncionario`),
  INDEX `fk_Tb_Funcionario_Tb_Pessoas1_idx` (`Tb_Pessoas_CPF` ASC) ,
  INDEX `fk_Tb_Funcionario_Tb_Loja1_idx` (`Tb_Loja_idLoja` ASC) ,
  CONSTRAINT `fk_Tb_Funcionario_Tb_Pessoas1`
    FOREIGN KEY (`Tb_Pessoas_CPF`)
    REFERENCES `iziImoveis`.`Tb_Pessoas` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tb_Funcionario_Tb_Loja1`
    FOREIGN KEY (`Tb_Loja_idLoja`)
    REFERENCES `iziImoveis`.`Tb_Loja` (`idLoja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iziImoveis`.`Tb_ImoveisAluguel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iziImoveis`.`Tb_ImoveisAluguel` (
  `idTb_ImoveisAluguel` INT NOT NULL,
  `tipo_de_Imovel` VARCHAR(45) NOT NULL,
  `tipo_de_oferta` VARCHAR(45) NOT NULL,
  `Tb_ContratoAluguel_idContratoAluguel` INT NOT NULL,
  `Tb_Proprietarios_idProprietarios` INT NOT NULL,
  `Tb_Regiao_idTb_Regiao` INT NOT NULL,
  `Tb_Funcionario_idFuncionario` INT NOT NULL,
  PRIMARY KEY (`idTb_ImoveisAluguel`),
  INDEX `fk_Tb_ImoveisAluguel_Tb_ContratoAluguel1_idx` (`Tb_ContratoAluguel_idContratoAluguel` ASC),
  INDEX `fk_Tb_ImoveisAluguel_Tb_Proprietarios1_idx` (`Tb_Proprietarios_idProprietarios` ASC),
  INDEX `fk_Tb_ImoveisAluguel_Tb_Regiao1_idx` (`Tb_Regiao_idTb_Regiao` ASC),
  INDEX `fk_Tb_ImoveisAluguel_Tb_Funcionario1_idx` (`Tb_Funcionario_idFuncionario` ASC),
  CONSTRAINT `fk_Tb_ImoveisAluguel_Tb_ContratoAluguel1`
    FOREIGN KEY (`Tb_ContratoAluguel_idContratoAluguel`)
    REFERENCES `iziImoveis`.`Tb_ContratoAluguel` (`idContratoAluguel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tb_ImoveisAluguel_Tb_Proprietarios1`
    FOREIGN KEY (`Tb_Proprietarios_idProprietarios`)
    REFERENCES `iziImoveis`.`Tb_Proprietarios` (`idProprietarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tb_ImoveisAluguel_Tb_Regiao1`
    FOREIGN KEY (`Tb_Regiao_idTb_Regiao`)
    REFERENCES `iziImoveis`.`Tb_Regiao` (`idTb_Regiao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tb_ImoveisAluguel_Tb_Funcionario1`
    FOREIGN KEY (`Tb_Funcionario_idFuncionario`)
    REFERENCES `iziImoveis`.`Tb_Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iziImoveis`.`Tb_Aluguel_Casa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iziImoveis`.`Tb_Aluguel_Casa` (
  `idAluguel_Casa` INT NOT NULL,
  `Tb_Imoveis_idTb_ImoveisAluguel` INT NOT NULL,
  `Titulo` VARCHAR(45) NULL,
  `Descrição` VARCHAR(45) NULL,
  `Numero_de_quartos` INT NULL,
  `Numero_de_banheiros` INT NULL,
  `Tamanho_da_area` FLOAT NULL,
  `Comodidades` VARCHAR(45) NULL,
  `Fotos` VARCHAR(45) NULL,
  `Disponibilidade` VARCHAR(45) NULL,
  `Regras_da_casa` VARCHAR(45) NULL,
  `Status_da_propriedade` VARCHAR(45) NULL,
  `Acessibilidades` CHAR NULL,
  `Aceita_animais` CHAR NULL,
  `avaliação` INT NULL,
  `Independente` CHAR NULL,
  `Endereco` VARCHAR(45) NULL,
  `Criacao_do_anuncio` DATETIME NULL,
  `Data_de_modificacao` DATETIME NULL,
  `Historico_de_aluguel` INT NULL,
  `Qt_de_visitas` INT NULL,
  PRIMARY KEY (`idAluguel_Casa`, `Tb_Imoveis_idTb_ImoveisAluguel`),
  INDEX `fk_Tb_Aluguel_Casa_Tb_Imoveis1_idx` (`Tb_Imoveis_idTb_ImoveisAluguel` ASC) ,
  CONSTRAINT `fk_Tb_Aluguel_Casa_Tb_Imoveis1`
    FOREIGN KEY (`Tb_Imoveis_idTb_ImoveisAluguel`)
    REFERENCES `iziImoveis`.`Tb_ImoveisAluguel` (`idTb_ImoveisAluguel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iziImoveis`.`Tb_Aluguel_Apartamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iziImoveis`.`Tb_Aluguel_Apartamento` (
  `idAluguel_Apartamento` INT NOT NULL,
  `Tb_Imoveis_idTb_ImoveisAluguel` INT NOT NULL,
  `Titulo` VARCHAR(45) NULL,
  `Descricao` VARCHAR(45) NULL,
  `Preco_do_condominio` FLOAT NULL,
  `Numero_de_Quartos` INT NULL,
  `Numero_de_Banheiros` INT NULL,
  `Tamanho_da_Area` FLOAT NULL,
  `Espaços_de_lazer` VARCHAR(45) NULL,
  `Vaga_na_garagem` CHAR NULL,
  `Comodidades` VARCHAR(45) NULL,
  `Fotos` VARCHAR(45) NULL,
  `Data_de_disponibilidade` DATETIME NULL,
  `Aceita_animais` CHAR NULL,
  `Data_de_criacao_do_anuncio` DATETIME NULL,
  `Data_de_modificacao` DATETIME NULL,
  `Avaliacao` INT NULL,
  `Acessibilidade` CHAR NULL,
  `Historico_de_aluguel` INT NULL,
  `Status_da_propriedade` VARCHAR(45) NULL,
  `Andar` INT NULL,
  `Qt_de_visitas` INT NULL,
  PRIMARY KEY (`idAluguel_Apartamento`, `Tb_Imoveis_idTb_ImoveisAluguel`),
  INDEX `fk_Tb_Aluguel_Apartamento_Tb_Imoveis1_idx` (`Tb_Imoveis_idTb_ImoveisAluguel` ASC) ,
  CONSTRAINT `fk_Tb_Aluguel_Apartamento_Tb_Imoveis1`
    FOREIGN KEY (`Tb_Imoveis_idTb_ImoveisAluguel`)
    REFERENCES `iziImoveis`.`Tb_ImoveisAluguel` (`idTb_ImoveisAluguel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iziImoveis`.`Tb_Aluguel_Kitnets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iziImoveis`.`Tb_Aluguel_Kitnets` (
  `idAluguel_Kitnets` INT NOT NULL,
  `Tb_Imoveis_idTb_ImoveisAluguel` INT NOT NULL,
  `Titulo` VARCHAR(45) NULL,
  `Descricao` VARCHAR(45) NULL,
  `Endereco` VARCHAR(45) NULL,
  `Tamanho_da_area` FLOAT NULL,
  `Comodidades` VARCHAR(45) NULL,
  `Fotos` VARCHAR(45) NULL,
  `Data_de_disponibilidade` DATETIME NULL,
  `Aceita_animais` CHAR NULL,
  `Avaliacao` INT NULL,
  `Status_da_propriedade` VARCHAR(45) NULL,
  `Acessibilidade` CHAR NULL,
  `Data_de_criacao_de_anuncio` DATETIME NULL,
  `Data_de_modificacao` DATETIME NULL,
  `Historico_de_aluguel` INT NULL,
  `Qt_de_visitas` INT NULL,
  PRIMARY KEY (`idAluguel_Kitnets`, `Tb_Imoveis_idTb_ImoveisAluguel`),
  INDEX `fk_Tb_Aluguel_Kitnets_Tb_Imoveis1_idx` (`Tb_Imoveis_idTb_ImoveisAluguel` ASC) ,
  CONSTRAINT `fk_Tb_Aluguel_Kitnets_Tb_Imoveis1`
    FOREIGN KEY (`Tb_Imoveis_idTb_ImoveisAluguel`)
    REFERENCES `iziImoveis`.`Tb_ImoveisAluguel` (`idTb_ImoveisAluguel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iziImoveis`.`Tb_Aluguel_Lofts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iziImoveis`.`Tb_Aluguel_Lofts` (
  `idAluguel_Lofts` INT NOT NULL,
  `Tb_Imoveis_idTb_ImoveisAluguel` INT NOT NULL,
  `Titulo` VARCHAR(45) NULL,
  `Descricao` VARCHAR(45) NULL,
  `Endereco` VARCHAR(45) NULL,
  `Numero_de_quartos` INT NULL,
  `Numero_de_banheiros` INT NULL,
  `Tamanho_da_area` FLOAT NULL,
  `Comodidades` VARCHAR(45) NULL,
  `Fotos` VARCHAR(45) NULL,
  `Data_de_disponibilidade` DATETIME NULL,
  `Avaliacao` INT NULL,
  `Status_da_propriedade` VARCHAR(45) NULL,
  `Acessibilidade` CHAR NULL,
  `Data_de_criacao_do_anuncio` DATETIME NULL,
  `Data_de_modificacao` DATETIME NULL,
  `Categoria` VARCHAR(45) NULL,
  `Historico_de_aluguel` INT NULL,
  `Qt_de_visitas` INT NULL,
  PRIMARY KEY (`idAluguel_Lofts`, `Tb_Imoveis_idTb_ImoveisAluguel`),
  INDEX `fk_Tb_Aluguel_Lofts_Tb_Imoveis1_idx` (`Tb_Imoveis_idTb_ImoveisAluguel` ASC) ,
  CONSTRAINT `fk_Tb_Aluguel_Lofts_Tb_Imoveis1`
    FOREIGN KEY (`Tb_Imoveis_idTb_ImoveisAluguel`)
    REFERENCES `iziImoveis`.`Tb_ImoveisAluguel` (`idTb_ImoveisAluguel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iziImoveis`.`Tb_Aluguel_Salas_Comerciais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iziImoveis`.`Tb_Aluguel_Salas_Comerciais` (
  `idAluguel_Salas_Comerciais` INT NOT NULL,
  `Tb_Imoveis_idTb_ImoveisAluguel` INT NOT NULL,
  `Titulo` VARCHAR(45) NULL,
  `Descricao` VARCHAR(45) NULL,
  `Endereco` VARCHAR(45) NULL,
  `contas_inclusas` CHAR NULL,
  `Tamanho_da_area` FLOAT NULL,
  `Espaco_equipado` CHAR NULL,
  `Fotos` VARCHAR(45) NULL,
  `Comodidades` VARCHAR(45) NULL,
  `Avaliacao` INT NULL,
  `Data_de_criacao_do_anuncios` DATETIME NULL,
  `Status_da_propriedade` VARCHAR(45) NULL,
  `Acessibilidade` CHAR NULL,
  `Data_de_disponibilidade` DATETIME NULL,
  `Data_de_modificacao` DATETIME NULL,
  `Historico_de_aluguel` INT NULL,
  `Qt_de_visitas` INT NULL,
  PRIMARY KEY (`idAluguel_Salas_Comerciais`, `Tb_Imoveis_idTb_ImoveisAluguel`),
  INDEX `fk_Tb_Aluguel_Salas_Comerciais_Tb_Imoveis1_idx` (`Tb_Imoveis_idTb_ImoveisAluguel` ASC) ,
  CONSTRAINT `fk_Tb_Aluguel_Salas_Comerciais_Tb_Imoveis1`
    FOREIGN KEY (`Tb_Imoveis_idTb_ImoveisAluguel`)
    REFERENCES `iziImoveis`.`Tb_ImoveisAluguel` (`idTb_ImoveisAluguel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iziImoveis`.`Tb_Aluguel_Galpoes_Industriais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iziImoveis`.`Tb_Aluguel_Galpoes_Industriais` (
  `idTb_Aluguel_Galpoes_Industriais` INT NOT NULL,
  `Tb_Imoveis_idTb_ImoveisAluguel` INT NOT NULL,
  `Titulo` VARCHAR(45) NULL,
  `Descricao` VARCHAR(45) NULL,
  `Endereco` VARCHAR(45) NULL,
  `Tamanho_da_area_de_armazenamento` FLOAT NULL,
  `Altura_do_teto` FLOAT NULL,
  `Capacidade_de_carga` FLOAT NULL,
  `Comodidades` VARCHAR(45) NULL,
  `Fotos` VARCHAR(45) NULL,
  `Data_de_disponibilidade` DATETIME NULL,
  `Avaliacao` INT NULL,
  `Status_do_galpao` VARCHAR(45) NULL,
  `Data_de_criacao_de_anuncio` DATETIME NULL,
  `Data_de_modificacao` DATETIME NULL,
  `Historico_de_aluguel` INT NULL,
  `Qt_de_visitas` INT NULL,
  PRIMARY KEY (`idTb_Aluguel_Galpoes_Industriais`, `Tb_Imoveis_idTb_ImoveisAluguel`),
  INDEX `fk_Tb_Aluguel_Galpoes_Industriais_Tb_Imoveis1_idx` (`Tb_Imoveis_idTb_ImoveisAluguel` ASC) ,
  CONSTRAINT `fk_Tb_Aluguel_Galpoes_Industriais_Tb_Imoveis1`
    FOREIGN KEY (`Tb_Imoveis_idTb_ImoveisAluguel`)
    REFERENCES `iziImoveis`.`Tb_ImoveisAluguel` (`idTb_ImoveisAluguel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iziImoveis`.`Tb_Aluguel_Espacos_de_Coworking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iziImoveis`.`Tb_Aluguel_Espacos_de_Coworking` (
  `idAluguel_Espacos_de_Coworking` INT NOT NULL,
  `Tb_Imoveis_idTb_ImoveisAluguel` INT NOT NULL,
  `Titulo` VARCHAR(45) NULL,
  `Descricao` VARCHAR(45) NULL,
  `Endereco` VARCHAR(45) NULL,
  `Precos_e_planos` FLOAT NULL,
  `Horario_de_funcionamento` VARCHAR(45) NULL,
  `Tamanho_e_capacidade` INT NULL,
  `Comodidades` VARCHAR(45) NULL,
  `Fotos` VARCHAR(45) NULL,
  `Data_de_disponibilidade` DATETIME NULL,
  `Acessibilidade` CHAR NULL,
  `Avaliacao` INT NULL,
  `Status_do_espaco` VARCHAR(45) NULL,
  `Data_de_criacao_do_anuncio` DATETIME NULL,
  `Data_de_modificacao` DATETIME NULL,
  `Redes_sociais` VARCHAR(45) NULL,
  `Historico_de_aluguel` INT NULL,
  `Qt_de_visitas` INT NULL,
  PRIMARY KEY (`Tb_Imoveis_idTb_ImoveisAluguel`, `idAluguel_Espacos_de_Coworking`),
  INDEX `fk_Tb_Aluguel_Espaços de Coworking_Tb_Imoveis1_idx` (`Tb_Imoveis_idTb_ImoveisAluguel` ASC) ,
  CONSTRAINT `fk_Tb_Aluguel_Espaços de Coworking_Tb_Imoveis1`
    FOREIGN KEY (`Tb_Imoveis_idTb_ImoveisAluguel`)
    REFERENCES `iziImoveis`.`Tb_ImoveisAluguel` (`idTb_ImoveisAluguel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iziImoveis`.`Tb_Aluguel_Lojas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iziImoveis`.`Tb_Aluguel_Lojas` (
  `idAluguel_Lojas` INT NOT NULL,
  `Tb_Imoveis_idTb_ImoveisAluguel` INT NOT NULL,
  `Titulo` VARCHAR(45) NULL,
  `Descricao` VARCHAR(45) NULL,
  `Tamanho_da_area` FLOAT NULL,
  `Comodidades` VARCHAR(45) NULL,
  `Fotos` VARCHAR(45) NULL,
  `Data_de_disponibilidade` DATETIME NULL,
  `Classificacao_do_uso` VARCHAR(45) NULL,
  `Status_da_propriedade` VARCHAR(45) NULL,
  `Data_de_criacao_do_anuncio` DATETIME NULL,
  `Data_de_modificacao` DATETIME NULL,
  `Historico_de_aluguel` INT NULL,
  `Qt_de_visitas` INT NULL,
  PRIMARY KEY (`idAluguel_Lojas`, `Tb_Imoveis_idTb_ImoveisAluguel`),
  INDEX `fk_Tb_Aluguel_Lojas_Tb_Imoveis1_idx` (`Tb_Imoveis_idTb_ImoveisAluguel` ASC) ,
  CONSTRAINT `fk_Tb_Aluguel_Lojas_Tb_Imoveis1`
    FOREIGN KEY (`Tb_Imoveis_idTb_ImoveisAluguel`)
    REFERENCES `iziImoveis`.`Tb_ImoveisAluguel` (`idTb_ImoveisAluguel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `iziImoveis`.`Tb_Aluguel_Hostels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iziImoveis`.`Tb_Aluguel_Hostels` (
  `idAluguel_Hostels` INT NOT NULL,
  `Tb_Imoveis_idTb_ImoveisAluguel` INT NOT NULL, 
  `Nome_do_Hostel` VARCHAR(45) NULL,
  `Descricao` VARCHAR(45) NULL,
  `Endereco` VARCHAR(45) NULL,
  `Preco_da_diaria` FLOAT NULL,
  `Individual_ou_compartilhada` VARCHAR(45) NULL,
  `Numero_de_camas` INT NULL,
  `Comodidades` VARCHAR(45) NULL,
  `Fotos` VARCHAR(45) NULL,
  `Disponibilidade` CHAR NULL,
  `Avaliacao` CHAR NULL,
  `Status_do_Hostel` VARCHAR(45) NULL,
  `Acessibilidades` CHAR NULL,
  `Data_de_criacao_de_anuncio` DATETIME NULL,
  `Data_de_Modificacao` DATETIME NULL,
  `Refeicoes_no_local` CHAR NULL,
  `Historico_de_aluguel` INT NULL,
  `Qt_de_visitas` INT NULL,
  PRIMARY KEY (`idAluguel_Hostels`, `Tb_Imoveis_idTb_ImoveisAluguel`),
  INDEX `fk_Tb_Aluguel_Hostels_Tb_Imoveis1_idx` (`Tb_Imoveis_idTb_ImoveisAluguel` ASC),
  CONSTRAINT `fk_Tb_Aluguel_Hostels_Tb_Imoveis1`
    FOREIGN KEY (`Tb_Imoveis_idTb_ImoveisAluguel`)
    REFERENCES `iziImoveis`.`Tb_ImoveisAluguel` (`idTb_ImoveisAluguel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iziImoveis`.`Tb_Aluguel_Casas_Compartilhadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iziImoveis`.`Tb_Aluguel_Casas_Compartilhadas` (
  `idAluguel_Casas_Compartilhadas` INT NOT NULL,
  `Tb_Imoveis_idTb_ImoveisAluguel` INT NOT NULL,
  `Titulo` VARCHAR(45) NULL,
  `Descricao` VARCHAR(45) NULL,
  `Endereco` VARCHAR(45) NULL,
  `Numero_de_quartos` INT NULL,
  `Numero_de_quartos_disponiveis` INT NULL,
  `Numero_de_banheiro` INT NULL,
  `Tamanho_da_area_comum` FLOAT NULL,
  `Comodidades` VARCHAR(45) NULL,
  `Fotos` VARCHAR(45) NULL,
  `Aceita_animais` CHAR NULL,
  `Data_de_disponibilidade` DATETIME NULL,
  `Avalicao` INT NULL,
  `Status_da_propriedade` VARCHAR(45) NULL,
  `Avaliacao` INT NULL,
  `Data_de_criacao_do_anuncio` DATETIME NULL,
  `Data_de_modificacao` DATETIME NULL,
  `Historico_de_aluguel` INT NULL,
  `Qt_de_visitas` INT NULL,
  PRIMARY KEY (`idAluguel_Casas_Compartilhadas`, `Tb_Imoveis_idTb_ImoveisAluguel`),
  INDEX `fk_Tb_Aluguel_Casas_Compartilhadas_Tb_Imoveis1_idx` (`Tb_Imoveis_idTb_ImoveisAluguel` ASC) ,
  CONSTRAINT `fk_Tb_Aluguel_Casas_Compartilhadas_Tb_Imoveis1`
    FOREIGN KEY (`Tb_Imoveis_idTb_ImoveisAluguel`)
    REFERENCES `iziImoveis`.`Tb_ImoveisAluguel` (`idTb_ImoveisAluguel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iziImoveis`.`Tb_Aluguel_Casas_Moveis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iziImoveis`.`Tb_Aluguel_Casas_Moveis` (
  `idAluguel_Casas_Moveis` INT NOT NULL,
  `Tb_Imoveis_idTb_ImoveisAluguel` INT NOT NULL,
  `Titulo` VARCHAR(45) NULL,
  `Descricao` VARCHAR(45) NULL,
  `Tipo_de_Trailer` VARCHAR(45) NULL,
  `Marca_e_Modelo` VARCHAR(45) NULL,
  `Comprimento` FLOAT NULL,
  `Capacidade_de_dormir` INT NULL,
  `Comodidades` VARCHAR(45) NULL,
  `Fotos` VARCHAR(45) NULL,
  `Preço_do_Seguro` FLOAT NULL,
  `Data_de_disponibilidade` DATETIME NULL,
  `Avaliacao` CHAR NULL,
  `Data_de_criacao_do_anuncio` DATETIME NULL,
  `Data_de_mudanca` DATETIME NULL,
  `Categoria` VARCHAR(45) NULL,
  `Localizacao_atual` VARCHAR(45) NULL,
  `Condicoes_do_trailer` VARCHAR(45) NULL,
  `Conexoes_e_Utilitarios` VARCHAR(45) NULL,
  `Historico_de_aluguel` INT NULL,
  `Qt_de_visitas` INT NULL,
  PRIMARY KEY (`idAluguel_Casas_Moveis`, `Tb_Imoveis_idTb_ImoveisAluguel`),
  INDEX `fk_Tb_Aluguel_Casas_Moveis_Tb_Imoveis1_idx` (`Tb_Imoveis_idTb_ImoveisAluguel` ASC),
  CONSTRAINT `fk_Tb_Aluguel_Casas_Moveis_Tb_Imoveis1`
    FOREIGN KEY (`Tb_Imoveis_idTb_ImoveisAluguel`)
    REFERENCES `iziImoveis`.`Tb_ImoveisAluguel` (`idTb_ImoveisAluguel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iziImoveis`.`Tb_Aluguel_Chales_ou_Casas_de_Campo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iziImoveis`.`Tb_Aluguel_Chales_ou_Casas_de_Campo` (
  `idAluguel_Chales_ou_Casas_de_Campo` INT NOT NULL,
  `Tb_Imoveis_idTb_ImoveisAluguel` INT NOT NULL,
  `Titulo` VARCHAR(45) NULL,
  `Descricao` VARCHAR(45) NULL,
  `Endereco` VARCHAR(45) NULL,
  `Numero_de_quartos` INT NULL,
  `Numero_de_banheiros` INT NULL,
  `Tamanho_da_area` FLOAT NULL,
  `Comodidades_rurais` VARCHAR(45) NULL,
  `Fotos` VARCHAR(45) NULL,
  `Data_de_disponibilidade` DATETIME NULL,
  `Aceita_animais` CHAR NULL,
  `Acessibilidade` CHAR NULL,
  `Avaliacao` INT NULL,
  `Status_da_propriedade` VARCHAR(45) NULL,
  `Historico_de_aluguel` INT NULL,
  `Qt_de_visitas` INT NULL,
  PRIMARY KEY (`idAluguel_Chales_ou_Casas_de_Campo`, `Tb_Imoveis_idTb_ImoveisAluguel`),
  INDEX `fk_Tb_Aluguel_Chales_ou_Casas_de_Campo_Tb_Imoveis1_idx` (`Tb_Imoveis_idTb_ImoveisAluguel` ASC) ,
  CONSTRAINT `fk_Tb_Aluguel_Chales_ou_Casas_de_Campo_Tb_Imoveis1`
    FOREIGN KEY (`Tb_Imoveis_idTb_ImoveisAluguel`)
    REFERENCES `iziImoveis`.`Tb_ImoveisAluguel` (`idTb_ImoveisAluguel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iziImoveis`.`Tb_Aluguel_Casas_de_Ferias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iziImoveis`.`Tb_Aluguel_Casas_de_Ferias` (
  `idAluguel_Casas_de_Ferias` INT NOT NULL,
  `Tb_Imoveis_idTb_ImoveisAluguel` INT NOT NULL,
  `Titulo` VARCHAR(45) NULL,
  `Descricao` VARCHAR(45) NULL,
  `Area_externa` CHAR NULL,
  `Vista` VARCHAR(45) NULL,
  `Atividades_proximas` VARCHAR(45) NULL,
  `Equipamento_de_lazer` VARCHAR(45) NULL,
  `Servico_adicionais` VARCHAR(45) NULL,
  `Estacionamento` CHAR NULL,
  `Acessibilidade` CHAR NULL,
  `Aceita_animais` CHAR NULL,
  `Distancia_ate_pontos_turisticos` FLOAT NULL,
  `Temperatura_media` FLOAT NULL,
  `Numero_minimo_de_noites` INT NULL,
  `Estilo_arquitetonico` VARCHAR(45) NULL,
  `Endereco` VARCHAR(45) NULL,
  `Avaliacao` INT NULL,
  `Historico_de_aluguel` INT NULL,
  `Status_da_propriedade` VARCHAR(45) NULL,
  `Qt_de_visitas` INT NULL,
  PRIMARY KEY (`idAluguel_Casas_de_Ferias`, `Tb_Imoveis_idTb_ImoveisAluguel`),
  INDEX `fk_Tb_Aluguel_Casas_de_Ferias_Tb_Imoveis1_idx` (`Tb_Imoveis_idTb_ImoveisAluguel` ASC) ,
  CONSTRAINT `fk_Tb_Aluguel_Casas_de_Ferias_Tb_Imoveis1`
    FOREIGN KEY (`Tb_Imoveis_idTb_ImoveisAluguel`)
    REFERENCES `iziImoveis`.`Tb_ImoveisAluguel` (`idTb_ImoveisAluguel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iziImoveis`.`Tb_Aluguel_Cobertura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iziImoveis`.`Tb_Aluguel_Cobertura` (
  `idAluguel_Cobertura` INT NOT NULL,
  `Tb_Imoveis_idTb_ImoveisAluguel` INT NOT NULL,
  `Titulo` VARCHAR(45) NULL,
  `Descricao` VARCHAR(45) NULL,
  `Preco_do_condominio` FLOAT NULL,
  `Numero_de_Quartos` INT NULL,
  `Numero_de_Banheiros` INT NULL,
  `Tamanho_da_Area` FLOAT NULL,
  `Espaços_de_lazer` VARCHAR(45) NULL,
  `Vaga_na_garagem` CHAR NULL,
  `Comodidades` VARCHAR(45) NULL,
  `Fotos` VARCHAR(45) NULL,
  `Data_de_disponibilidade` DATETIME NULL,
  `Aceita_animais` CHAR NULL,
  `Data_de_criacao_do_anuncio` DATETIME NULL,
  `Data_de_modificacao` DATETIME NULL,
  `Avaliacao` INT NULL,
  `Acessibilidade` CHAR NULL,
  `Meios_de_segurança` VARCHAR(45) NULL,
  `Historico_de_aluguel` INT NULL,
  `Status_da_propriedade` VARCHAR(45) NULL,
  `Qt_de_visitas` INT NULL,
  PRIMARY KEY (`idAluguel_Cobertura`, `Tb_Imoveis_idTb_ImoveisAluguel`),
  INDEX `fk_Tb_Aluguel_Cobertura_Tb_Imoveis1_idx` (`Tb_Imoveis_idTb_ImoveisAluguel` ASC) ,
  CONSTRAINT `fk_Tb_Aluguel_Cobertura_Tb_Imoveis1`
    FOREIGN KEY (`Tb_Imoveis_idTb_ImoveisAluguel`)
    REFERENCES `iziImoveis`.`Tb_ImoveisAluguel` (`idTb_ImoveisAluguel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iziImoveis`.`Tb_Compradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iziImoveis`.`Tb_Compradores` (
  `Codigo_do_comprador` INT NOT NULL,
  `Profissao` VARCHAR(45) NULL,
  `Renda_anual` FLOAT NULL,
  `Preferencia_de_imoveis` VARCHAR(45) NULL,
  `Orcamento` FLOAT NULL,
  `Prazo_de_compra` INT NULL,
  `Financiamento` CHAR NULL,
  `Possui_veiculo` CHAR NULL,
  `Tb_Pessoas_CPF` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`Codigo_do_comprador`),
  INDEX `fk_Tb_Compradores_Tb_Pessoas1_idx` (`Tb_Pessoas_CPF` ASC) ,
  CONSTRAINT `fk_Tb_Compradores_Tb_Pessoas1`
    FOREIGN KEY (`Tb_Pessoas_CPF`)
    REFERENCES `iziImoveis`.`Tb_Pessoas` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iziImoveis`.`Tb_Contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iziImoveis`.`Tb_Contrato` (
  `idContrato` INT NOT NULL,
  `Data_de_assinatura` DATETIME NULL,
  `Termos_e_condicoes` VARCHAR(45) NULL,
  `Valor_de_entrada` FLOAT NULL,
  `Valor_da_parcela` FLOAT NULL,
  `Porcentagem_do_site` float NULL,
  `Qt_de_parcelas` INT NULL,
  `Escritura_do_imovel` CHAR NULL,
  `Algum_processo_em_andamento` CHAR NULL,
  `Data_de_mudanca` DATE NULL,
  `Tb_Compradores_Codigo_do_comprador` INT NOT NULL,
  PRIMARY KEY (`idContrato`),
  INDEX `fk_Tb_Contrato_Tb_Compradores1_idx` (`Tb_Compradores_Codigo_do_comprador` ASC) ,
  CONSTRAINT `fk_Tb_Contrato_Tb_Compradores1`
    FOREIGN KEY (`Tb_Compradores_Codigo_do_comprador`)
    REFERENCES `iziImoveis`.`Tb_Compradores` (`Codigo_do_comprador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iziImoveis`.`Tb_ImoveisVendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iziImoveis`.`Tb_ImoveisVendas` (
  `idTb_ImoveisVendas` INT NOT NULL,
  `tipo_de_Imovel` VARCHAR(45) NOT NULL, -- Correção aqui
  `tipo_de_oferta` VARCHAR(45) NOT NULL,
  `Subsidios_do_gorveno` CHAR NULL,
  `Disponivel_para_negociacao` CHAR NULL,
  `Tb_Proprietarios_idProprietarios` INT NOT NULL,
  `Tb_Contrato_idContrato` INT NOT NULL,
  `Tb_Funcionario_idFuncionario` INT NOT NULL,
  `Tb_Regiao_idTb_Regiao` INT NOT NULL,
  PRIMARY KEY (`idTb_ImoveisVendas`),
  INDEX `fk_Tb_ImoveisVendas_Tb_Proprietarios1_idx` (`Tb_Proprietarios_idProprietarios` ASC),
  INDEX `fk_Tb_ImoveisVendas_Tb_Contrato1_idx` (`Tb_Contrato_idContrato` ASC),
  INDEX `fk_Tb_ImoveisVendas_Tb_Funcionario1_idx` (`Tb_Funcionario_idFuncionario` ASC),
  INDEX `fk_Tb_ImoveisVendas_Tb_Regiao1_idx` (`Tb_Regiao_idTb_Regiao` ASC),
  CONSTRAINT `fk_Tb_ImoveisVendas_Tb_Proprietarios1`
    FOREIGN KEY (`Tb_Proprietarios_idProprietarios`)
    REFERENCES `iziImoveis`.`Tb_Proprietarios` (`idProprietarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tb_ImoveisVendas_Tb_Contrato1`
    FOREIGN KEY (`Tb_Contrato_idContrato`)
    REFERENCES `iziImoveis`.`Tb_Contrato` (`idContrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tb_ImoveisVendas_Tb_Funcionario1`
    FOREIGN KEY (`Tb_Funcionario_idFuncionario`)
    REFERENCES `iziImoveis`.`Tb_Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tb_ImoveisVendas_Tb_Regiao1`
    FOREIGN KEY (`Tb_Regiao_idTb_Regiao`)
    REFERENCES `iziImoveis`.`Tb_Regiao` (`idTb_Regiao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `iziImoveis`.`Tb_Compras_Casa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iziImoveis`.`Tb_Compras_Casa` (
  `idCompras_Casa` INT NOT NULL,
  `Tb_ImoveisVendas_idTb_ImoveisVendas` INT NOT NULL,
  `Endereco` VARCHAR(45) NULL,
  `Numero_de_quartos` INT NULL,
  `Numero_de_banheiros` INT NULL,
  `Tamanho_da_casa` FLOAT NULL,
  `Preco_de_venda` FLOAT NULL,
  `Status_do_imovel` VARCHAR(45) NULL,
  `Ano_de_construcao` DATE NULL,
  `Fotos` VARCHAR(45) NULL,
  `Acessibilidade` CHAR NULL,
  `Data_de_listagem` DATETIME NULL,
  `Data_de_termino_de_listagem` DATETIME NULL,
  `Valor_de_mercado` FLOAT NULL,
  PRIMARY KEY (`idCompras_Casa`, `Tb_ImoveisVendas_idTb_ImoveisVendas`),
  INDEX `fk_Tb_Compras_Casa_Tb_ImoveisVendas1_idx` (`Tb_ImoveisVendas_idTb_ImoveisVendas` ASC) ,
  CONSTRAINT `fk_Tb_Compras_Casa_Tb_ImoveisVendas1`
    FOREIGN KEY (`Tb_ImoveisVendas_idTb_ImoveisVendas`)
    REFERENCES `iziImoveis`.`Tb_ImoveisVendas` (`idTb_ImoveisVendas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iziImoveis`.`Tb_Compras_Apartamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iziImoveis`.`Tb_Compras_Apartamento` (
  `idCompras_Apartamento` INT NOT NULL,
  `Tb_ImoveisVendas_idTb_ImoveisVendas` INT NOT NULL,
  `Endereco` VARCHAR(45) NULL,
  `Numero_de_quartos` INT NULL,
  `Numero_de_banheiros` INT NULL,
  `Tamanho_do_apartamento` FLOAT NULL,
  `Preco_da_venda` FLOAT NULL,
  `Preco_do_condominio` FLOAT NULL,
  `Andar` INT NULL,
  `Status_do_imovel` VARCHAR(45) NULL,
  `Acessibilidade` CHAR NULL,
  `Ano_de_construção` DATE NULL,
  `Fotos` VARCHAR(45) NULL,
  `Comodidades` VARCHAR(45) NULL,
  `Data_de_listagem` DATETIME NULL,
  `Data_de_termino_de_listagem` DATETIME NULL,
  `Valor_de_mercado` FLOAT NULL,
  PRIMARY KEY (`idCompras_Apartamento`, `Tb_ImoveisVendas_idTb_ImoveisVendas`),
  INDEX `fk_Tb_Compras_Apartamento_Tb_ImoveisVendas1_idx` (`Tb_ImoveisVendas_idTb_ImoveisVendas` ASC) ,
  CONSTRAINT `fk_Tb_Compras_Apartamento_Tb_ImoveisVendas1`
    FOREIGN KEY (`Tb_ImoveisVendas_idTb_ImoveisVendas`)
    REFERENCES `iziImoveis`.`Tb_ImoveisVendas` (`idTb_ImoveisVendas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iziImoveis`.`Tb_Compras_Condominio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iziImoveis`.`Tb_Compras_Condominio` (
  `idCompras_Condominio` INT NOT NULL,
  `Tb_ImoveisVendas_idTb_ImoveisVendas` INT NOT NULL,
  `Descricao` VARCHAR(45) NULL,
  `Valor_de_compra` FLOAT NULL,
  `Data_de_listagem` DATETIME NULL,
  `Data_de_termino_de_listagem` DATETIME NULL,
  `Categoria` VARCHAR(45) NULL,
  `Acessibilidade` CHAR NULL,
  `Valor_de_mercado` FLOAT NULL,
  PRIMARY KEY (`idCompras_Condominio`, `Tb_ImoveisVendas_idTb_ImoveisVendas`),
  INDEX `fk_Tb_Compras_Condominio_Tb_ImoveisVendas1_idx` (`Tb_ImoveisVendas_idTb_ImoveisVendas` ASC) ,
  CONSTRAINT `fk_Tb_Compras_Condominio_Tb_ImoveisVendas1`
    FOREIGN KEY (`Tb_ImoveisVendas_idTb_ImoveisVendas`)
    REFERENCES `iziImoveis`.`Tb_ImoveisVendas` (`idTb_ImoveisVendas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iziImoveis`.`Tb_Compras_Casas_Duplex_ou_Triplex`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iziImoveis`.`Tb_Compras_Casas_Duplex_ou_Triplex` (
  `idCompras_Casas_Duplex_ou_Triplex` INT NOT NULL,
  `Tb_ImoveisVendas_idTb_ImoveisVendas` INT NOT NULL,
  `Tipo_de_imovel` VARCHAR(45) NULL,
  `Endereco` VARCHAR(45) NULL,
  `Numero_de_unidades` INT NULL,
  `Numero_de_quartos` INT NULL,
  `Numero_de_banheiros` INT NULL,
  `Tamanho_total` FLOAT NULL,
  `Preco_de_venda` FLOAT NULL,
  `Status_do_imovel` VARCHAR(45) NULL,
  `Acessibilidade` CHAR NULL,
  `Ano_de_costrucao` DATE NULL,
  `Fotos` VARCHAR(45) NULL,
  `Data_de_listagem` DATETIME NULL,
  `Data_de_termino_de_listagem` DATETIME NULL,
  `Valor_de_mercado` FLOAT NULL,
  PRIMARY KEY (`idCompras_Casas_Duplex_ou_Triplex`, `Tb_ImoveisVendas_idTb_ImoveisVendas`),
  INDEX `fk_Tb_Compras_Casas_Duplex_ou_Triplex_Tb_ImoveisVendas1_idx` (`Tb_ImoveisVendas_idTb_ImoveisVendas` ASC) ,
  CONSTRAINT `fk_Tb_Compras_Casas_Duplex_ou_Triplex_Tb_ImoveisVendas1`
    FOREIGN KEY (`Tb_ImoveisVendas_idTb_ImoveisVendas`)
    REFERENCES `iziImoveis`.`Tb_ImoveisVendas` (`idTb_ImoveisVendas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iziImoveis`.`Tb_Compras_Terrenos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iziImoveis`.`Tb_Compras_Terrenos` (
  `idCompras_Terrenos` INT NOT NULL,
  `Tb_ImoveisVendas_idTb_ImoveisVendas` INT NOT NULL,
  `Localizacao` VARCHAR(45) NULL,
  `Area_do_terreno` FLOAT NULL,
  `Zona_de_uso` VARCHAR(45) NULL,
  `Topografia` VARCHAR(45) NULL,
  `Preco_de_venda` FLOAT NULL,
  `Status_do_terreno` VARCHAR(45) NULL,
  `Descricao` VARCHAR(45) NULL,
  `Fotos` VARCHAR(45) NULL,
  `Data_de_listagem` DATETIME NULL,
  `Data_de_termino_de_listagem` DATETIME NULL,
  `Valor_de_mercado` FLOAT NULL,
  PRIMARY KEY (`idCompras_Terrenos`, `Tb_ImoveisVendas_idTb_ImoveisVendas`),
  INDEX `fk_Tb_Compras_Terrenos_Tb_ImoveisVendas1_idx` (`Tb_ImoveisVendas_idTb_ImoveisVendas` ASC) ,
  CONSTRAINT `fk_Tb_Compras_Terrenos_Tb_ImoveisVendas1`
    FOREIGN KEY (`Tb_ImoveisVendas_idTb_ImoveisVendas`)
    REFERENCES `iziImoveis`.`Tb_ImoveisVendas` (`idTb_ImoveisVendas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iziImoveis`.`Tb_Compras_Casas_de_Campo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iziImoveis`.`Tb_Compras_Casas_de_Campo` (
  `idCompras_Casas_de_Campo` INT NOT NULL,
  `Tb_ImoveisVendas_idTb_ImoveisVendas` INT NOT NULL,
  `Endereco` VARCHAR(45) NULL,
  `Numero-de_quartos` INT NULL,
  `Numero_de_banheiros` INT NULL,
  `Tamanho_do_terreno` FLOAT NULL,
  `Tamanho_da_casa` FLOAT NULL,
  `Preco_da_venda` FLOAT NULL,
  `Status_do_imovel` VARCHAR(45) NULL,
  `Ano_de_construcao` DATE NULL,
  `Descricao` VARCHAR(45) NULL,
  `Acessibilidade` CHAR NULL,
  `Fotos` VARCHAR(45) NULL,
  `Data_de_listagem` DATETIME NULL,
  `Data_de_termino_de_listagem` DATETIME NULL,
  `Valor_de_mercado` FLOAT NULL,
  PRIMARY KEY (`idCompras_Casas_de_Campo`, `Tb_ImoveisVendas_idTb_ImoveisVendas`),
  INDEX `fk_Tb_Compras_Casas_de_Campo_Tb_ImoveisVendas1_idx` (`Tb_ImoveisVendas_idTb_ImoveisVendas` ASC) ,
  CONSTRAINT `fk_Tb_Compras_Casas_de_Campo_Tb_ImoveisVendas1`
    FOREIGN KEY (`Tb_ImoveisVendas_idTb_ImoveisVendas`)
    REFERENCES `iziImoveis`.`Tb_ImoveisVendas` (`idTb_ImoveisVendas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iziImoveis`.`Tb_Compras_Casas_Moveis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iziImoveis`.`Tb_Compras_Casas_Moveis` (
  `idCompras_Casas_Moveis` INT NOT NULL,
  `Tb_ImoveisVendas_idTb_ImoveisVendas` INT NOT NULL,
  `Valor_do_imovel` FLOAT NULL,
  `Conexoes_e_utilitarios` VARCHAR(45) NULL,
  `Condicoes_do_trailer` VARCHAR(45) NULL,
  `Categorias` VARCHAR(45) NULL,
  `Numeros_de_banheiro` INT NULL,
  `Capacidade_de_cama` INT NULL,
  `Tamanho` FLOAT NULL,
  `Status_do_imovel` VARCHAR(45) NULL,
  `Ano_de_construcao` DATE NULL,
  `Caracteristicas_especiais` VARCHAR(45) NULL,
  `Acessibilidade` CHAR NULL,
  `Fotos` VARCHAR(45) NULL,
  `Data_de_listagem` DATETIME NULL,
  `Dta_de_termino_de_listagem` DATETIME NULL,
  `Valor_de_mercado` FLOAT NULL,
  PRIMARY KEY (`idCompras_Casas_Moveis`, `Tb_ImoveisVendas_idTb_ImoveisVendas`),
  INDEX `fk_Tb_Compras_Casas_Moveis_Tb_ImoveisVendas1_idx` (`Tb_ImoveisVendas_idTb_ImoveisVendas` ASC) ,
  CONSTRAINT `fk_Tb_Compras_Casas_Moveis_Tb_ImoveisVendas1`
    FOREIGN KEY (`Tb_ImoveisVendas_idTb_ImoveisVendas`)
    REFERENCES `iziImoveis`.`Tb_ImoveisVendas` (`idTb_ImoveisVendas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iziImoveis`.`Tb_Compras_Fazendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iziImoveis`.`Tb_Compras_Fazendas` (
  `idCompras_Fazendas` INT NOT NULL,
  `Tb_ImoveisVendas_idTb_ImoveisVendas` INT NOT NULL,
  `Nome_da_fazenda` VARCHAR(45) NULL,
  `Localizacao` VARCHAR(45) NULL,
  `Area_total` FLOAT NULL,
  `Tipo_de_fazenda` VARCHAR(45) NULL,
  `Infraestrutura` VARCHAR(45) NULL,
  `Preco_de_venda` FLOAT NULL,
  `Status_da_fazenda` VARCHAR(45) NULL,
  `Fotos` VARCHAR(45) NULL,
  `Caracteristicas` VARCHAR(45) NULL,
  `Data_de_listagem` DATETIME NULL,
  `Data_de_termino_de_listagem` DATETIME NULL,
  `Valor_de_mercado` FLOAT NULL,
  PRIMARY KEY (`idCompras_Fazendas`, `Tb_ImoveisVendas_idTb_ImoveisVendas`),
  INDEX `fk_Tb_Compras_Fazendas_Tb_ImoveisVendas1_idx` (`Tb_ImoveisVendas_idTb_ImoveisVendas` ASC) ,
  CONSTRAINT `fk_Tb_Compras_Fazendas_Tb_ImoveisVendas1`
    FOREIGN KEY (`Tb_ImoveisVendas_idTb_ImoveisVendas`)
    REFERENCES `iziImoveis`.`Tb_ImoveisVendas` (`idTb_ImoveisVendas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iziImoveis`.`Tb_Despesas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iziImoveis`.`Tb_Despesas` (
  `idDespesas` INT NOT NULL,
  `Valor_da_despesa` FLOAT NULL,
  `Categoria_da_despesa` VARCHAR(45) NULL,
  `Data_da_despesa` DATE NULL,
  `Descricao_da_despesa` VARCHAR(45) NULL,
  `Tb_ImoveisVendas_idTb_ImoveisVendas` INT NOT NULL,
  `Tb_ImoveisVendas_Tb_Proprietarios_CPF` INT NOT NULL,
  `Tb_ImoveisVendas_Tb_Regiao_idTb_Regiao` INT NOT NULL,
  PRIMARY KEY (`idDespesas`),
  INDEX `fk_Tb_Despesas_Tb_ImoveisVendas1_idx` (`Tb_ImoveisVendas_idTb_ImoveisVendas` ASC, `Tb_ImoveisVendas_Tb_Proprietarios_CPF` ASC, `Tb_ImoveisVendas_Tb_Regiao_idTb_Regiao` ASC) ,
  CONSTRAINT `fk_Tb_Despesas_Tb_ImoveisVendas1`
    FOREIGN KEY (`Tb_ImoveisVendas_idTb_ImoveisVendas`)
    REFERENCES `iziImoveis`.`Tb_ImoveisVendas` (`idTb_ImoveisVendas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iziImoveis`.`Tb_Despesas_imovel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iziImoveis`.`Tb_Despesas_imovel` (
  `idDespesas_imovel` INT NOT NULL,
  `Descricao_da_despeca` VARCHAR(45) NULL,
  `Data_da_despesa` DATE NULL,
  `Categoria_da_despesa` VARCHAR(45) NULL,
  `Valor_da_despesa` FLOAT NULL,
  `Tb_ImoveisAluguel_idTb_ImoveisAluguel` INT NOT NULL,
  `Tb_ImoveisAluguel_Tb_Proprietarios_CPF` INT NOT NULL,
  `Tb_ImoveisAluguel_Tb_Regiao_idTb_Regiao` INT NOT NULL,
  PRIMARY KEY (`idDespesas_imovel`),
  INDEX `fk_Tb_Despesas_imovel_Tb_ImoveisAluguel1_idx` (`Tb_ImoveisAluguel_idTb_ImoveisAluguel` ASC, `Tb_ImoveisAluguel_Tb_Proprietarios_CPF` ASC, `Tb_ImoveisAluguel_Tb_Regiao_idTb_Regiao` ASC) ,
  CONSTRAINT `fk_Tb_Despesas_imovel_Tb_ImoveisAluguel1`
    FOREIGN KEY (`Tb_ImoveisAluguel_idTb_ImoveisAluguel`)
    REFERENCES `iziImoveis`.`Tb_ImoveisAluguel` (`idTb_ImoveisAluguel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iziImoveis`.`Tb_Transacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iziImoveis`.`Tb_Transacoes` (
  `idTransacoes` INT NOT NULL,
  `Data_da_transacao` DATETIME NULL,
  `Valor_da_Transacao` FLOAT NULL,
  `Detalhes_da_transacao` VARCHAR(45) NULL,
  `Metodos_de_pagamento` VARCHAR(45) NULL,
  `Historico_de_pagamento` INT NULL,
  `Tb_Locatarios_Codigo_do_locatario` INT NOT NULL,
  `Tb_ImoveisAluguel_idTb_ImoveisAluguel` INT NOT NULL,
  `Tb_ImoveisAluguel_Tb_Proprietarios_CPF` INT NOT NULL,
  `Tb_ImoveisAluguel_Tb_Regiao_idTb_Regiao` INT NOT NULL,
  PRIMARY KEY (`idTransacoes`),
  INDEX `fk_Tb_Transacoes_Tb_Locatarios1_idx` (`Tb_Locatarios_Codigo_do_locatario` ASC) ,
  INDEX `fk_Tb_Transacoes_Tb_ImoveisAluguel1_idx` (`Tb_ImoveisAluguel_idTb_ImoveisAluguel` ASC, `Tb_ImoveisAluguel_Tb_Proprietarios_CPF` ASC, `Tb_ImoveisAluguel_Tb_Regiao_idTb_Regiao` ASC) ,
  CONSTRAINT `fk_Tb_Transacoes_Tb_Locatarios1`
    FOREIGN KEY (`Tb_Locatarios_Codigo_do_locatario`)
    REFERENCES `iziImoveis`.`Tb_Locatarios` (`Codigo_do_locatario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tb_Transacoes_Tb_ImoveisAluguel1`
    FOREIGN KEY (`Tb_ImoveisAluguel_idTb_ImoveisAluguel`)
    REFERENCES `iziImoveis`.`Tb_ImoveisAluguel` (`idTb_ImoveisAluguel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iziImoveis`.`Tb_Compras_Casa_de_ferias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iziImoveis`.`Tb_Compras_Casa_de_ferias` (
  `idCompras_Casa` INT NOT NULL,
  `Tb_ImoveisVendas_idTb_ImoveisVendas` INT NOT NULL,
  `Endereco` VARCHAR(45) NULL,
  `Numero_de_quartos` INT NULL,
  `Numero_de_banheiros` INT NULL,
  `Tamanho_da_casa` FLOAT NULL,
  `Preco_de_venda` FLOAT NULL,
  `Status_do_imovel` VARCHAR(45) NULL,
  `Ano_de_construcao` DATE NULL,
  `Fotos` VARCHAR(45) NULL,
  `Acessibilidade` CHAR NULL,
  `Data_de_listagem` DATETIME NULL,
  `Data_de_termino_de_listagem` DATETIME NULL,
  `Ponto_turistico` VARCHAR(45) NULL,
  `Media_de_temperatura` FLOAT NULL,
  `Valor_de_mercado` FLOAT NULL,
  PRIMARY KEY (`idCompras_Casa`, `Tb_ImoveisVendas_idTb_ImoveisVendas`),
  INDEX `fk_Tb_Compras_Casa_Tb_ImoveisVendas1_idx` (`Tb_ImoveisVendas_idTb_ImoveisVendas` ASC) ,
  CONSTRAINT `fk_Tb_Compras_Casa_Tb_ImoveisVendas10`
    FOREIGN KEY (`Tb_ImoveisVendas_idTb_ImoveisVendas`)
    REFERENCES `iziImoveis`.`Tb_ImoveisVendas` (`idTb_ImoveisVendas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iziImoveis`.`Tb_Consolida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iziImoveis`.`Tb_Consolida` (
  `idTb_caixa` INT NOT NULL,
  `Mes_de_referencia` DATE NULL,
  `Tb_Contrato_idContrato` INT NOT NULL,
  `Tb_Transacoes_idTransacoes` INT NOT NULL,
  PRIMARY KEY (`idTb_caixa`),
  INDEX `fk_Tb_Consolida_Tb_Contrato1_idx` (`Tb_Contrato_idContrato` ASC) ,
  INDEX `fk_Tb_Consolida_Tb_Transacoes1_idx` (`Tb_Transacoes_idTransacoes` ASC) ,
  CONSTRAINT `fk_Tb_Consolida_Tb_Contrato1`
    FOREIGN KEY (`Tb_Contrato_idContrato`)
    REFERENCES `iziImoveis`.`Tb_Contrato` (`idContrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tb_Consolida_Tb_Transacoes1`
    FOREIGN KEY (`Tb_Transacoes_idTransacoes`)
    REFERENCES `iziImoveis`.`Tb_Transacoes` (`idTransacoes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iziImoveis`.`Tb_anuncio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iziImoveis`.`Tb_anuncio` (
  `idTb_anuncio` INT NOT NULL,
  `Data_de_anuncio` DATE NULL,
  `Valor` FLOAT NULL,
  `Meio_de_anuncio` VARCHAR(45) NULL,
  `publico_alvo` VARCHAR(45) NULL,
  `Tb_Consolida_idTb_caixa` INT NOT NULL,
  PRIMARY KEY (`idTb_anuncio`),
  INDEX `fk_Tb_anuncio_Tb_Consolida1_idx` (`Tb_Consolida_idTb_caixa` ASC) ,
  CONSTRAINT `fk_Tb_anuncio_Tb_Consolida1`
    FOREIGN KEY (`Tb_Consolida_idTb_caixa`)
    REFERENCES `iziImoveis`.`Tb_Consolida` (`idTb_caixa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
