insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (1, '0 Amoth Drive', 'Rondônia', 'Vila Mariana');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (2, '0683 Moulton Park', 'Mato Grosso do Sul', 'Santa Teresa');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (3, '22382 Crescent Oaks Place', 'Minas Gerais', 'Rio Vermelho');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (4, '74055 Doe Crossing Center', 'Roraima', 'Botafogo');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (5, '95 Lien Pass', 'Espírito Santo', 'Tijuca');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (6, '619 Bowman Trail', 'Ceará', 'Morro da Conceição');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (7, '41796 Crowley Court', 'Alagoas', 'Farol');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (8, '932 Troy Junction', 'Alagoas', 'Lapa');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (9, '4 Doe Crossing Court', 'Santa Catarina', 'Rio Vermelho');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (10, '43 Dapin Avenue', 'Sergipe.', 'Petrópolis');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (11, '4465 Manley Crossing', 'Piauí', 'Farol');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (12, '9406 Linden Terrace', 'Sergipe.', 'Jardim Paulista');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (13, '62 Fremont Lane', 'Rondônia', 'Barra da Tijuca');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (14, '43 Di Loreto Parkway', 'Acre', 'Jardim Guanabara.');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (15, '59334 Grasskamp Avenue', 'Bahia', 'Flamengo');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (16, '0471 Miller Parkway', 'Rio de Janeiro', 'Morro da Conceição');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (17, '07 Lighthouse Bay Lane', 'Paraná', 'Petrópolis');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (18, '51018 Summerview Plaza', 'Espírito Santo', 'Vila Mariana');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (19, '835 Troy Street', 'Ceará', 'Barra Funda');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (20, '27 Ryan Drive', 'Ceará', 'Jardim Paulista');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (21, '0320 Schiller Way', 'Rondônia', 'Tijuca');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (22, '7 Gina Drive', 'Pará', 'Meireles');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (23, '32708 Maywood Plaza', 'Rio Grande do Norte', 'Bela Vista');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (24, '07272 Fisk Street', 'Rio de Janeiro', 'Copacabana');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (25, '44770 Veith Pass', 'Espírito Santo', 'Vila Mariana');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (26, '3 1st Pass', 'São Paulo', 'Morumbi');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (27, '1341 Meadow Ridge Trail', 'Maranhão', 'Santo Amaro');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (28, '86162 Bultman Point', 'Rio de Janeiro', 'Consolação');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (29, '20716 Cherokee Circle', 'Amapá', 'Santo Amaro');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (30, '26 Myrtle Road', 'Espírito Santo', 'Vila Madalena');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (31, '628 Birchwood Avenue', 'Acre', 'Ipanema');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (32, '74980 Judy Crossing', 'Pernambuco', 'Centro');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (33, '287 Waywood Center', 'Rio de Janeiro', 'Moema');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (34, '1 Bay Avenue', 'Paraná', 'Botafogo');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (35, '88 Hovde Place', 'Mato Grosso do Sul', 'Praia do Canto');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (36, '096 Namekagon Terrace', 'Espírito Santo', 'Praia do Canto');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (37, '4553 Bellgrove Hill', 'Rio Grande do Norte', 'Boqueirão');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (38, '8 Sunbrook Junction', 'Minas Gerais', 'Santo Antônio');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (39, '3204 Northport Place', 'Sergipe.', 'Centro');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (40, '40161 Corben Place', 'Distrito Federal', 'Centro');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (41, '38 Eagle Crest Alley', 'Pará', 'Centro');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (42, '265 Blaine Terrace', 'Pernambuco', 'Tijuca');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (43, '9719 Eastlawn Plaza', 'Minas Gerais', 'Copacabana');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (44, '6912 Monica Alley', 'Acre', 'Laranjeiras');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (45, '0 International Plaza', 'Ceará', 'Savassi');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (46, '18590 Manley Drive', 'Minas Gerais', 'Consolação');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (47, '06615 Vernon Junction', 'Espírito Santo', 'Botafogo');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (48, '2128 Fremont Street', 'Roraima', 'Lapa');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (49, '9 Basil Avenue', 'Roraima', 'Santo Antônio');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (50, '25 Hagan Point', 'Piauí', 'Copacabana');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (51, '7 Northwestern Center', 'Piauí', 'Jardim Guanabara.');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (52, '9738 Fulton Street', 'Amazonas', 'Leblon');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (53, '3 Badeau Junction', 'Piauí', 'Glória');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (54, '8 Muir Alley', 'Mato Grosso', 'Cambuí');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (55, '3115 Acker Center', 'Mato Grosso', 'Moinhos de Vento');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (56, '7 Bultman Lane', 'Alagoas', 'Petrópolis');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (57, '3853 Rockefeller Road', 'Pernambuco', 'Rio Vermelho');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (58, '8 New Castle Hill', 'Minas Gerais', 'Jardim Paulista');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (59, '36908 Miller Pass', 'Roraima', 'Santo Amaro');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (60, '5214 American Ash Way', 'Sergipe.', 'Flamengo');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (61, '65159 Vermont Center', 'Alagoas', 'Consolação');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (62, '3 Larry Alley', 'Paraná', 'Pituba');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (63, '1798 Anhalt Point', 'Rio de Janeiro', 'Cambuí');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (64, '87121 Logan Hill', 'Rondônia', 'Centro');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (65, '35802 1st Lane', 'Goiás', 'Lourdes');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (66, '0243 East Point', 'Alagoas', 'Tijuca');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (67, '1 Ohio Circle', 'São Paulo', 'Centro');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (68, '04781 Crest Line Drive', 'Santa Catarina', 'Santo Amaro');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (69, '87 Shopko Alley', 'Minas Gerais', 'Pituba');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (70, '888 Lakewood Gardens Pass', 'Roraima', 'Centro');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (71, '44 Fair Oaks Park', 'Paraná', 'Glória');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (72, '2 Weeping Birch Pass', 'Roraima', 'Jardim Guanabara.');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (73, '3124 Leroy Way', 'Distrito Federal', 'Jardim Europa');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (74, '7 Bartillon Terrace', 'Rondônia', 'Lapa');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (75, '497 Lawn Plaza', 'Espírito Santo', 'Barra Funda');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (76, '9042 Waywood Point', 'Pará', 'Jardim Paulista');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (77, '521 Forest Circle', 'Paraná', 'Vila Mariana');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (78, '20818 Northwestern Drive', 'Paraná', 'Caminho das Árvores');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (79, '510 Katie Circle', 'Roraima', 'Praia do Canto');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (80, '5 John Wall Way', 'Ceará', 'Barra Funda');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (81, '072 Eagan Street', 'Rio Grande do Sul', 'Farol');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (82, '807 Grim Parkway', 'Paraíba', 'Laranjeiras');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (83, '9 Miller Hill', 'Alagoas', 'Rio Vermelho');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (84, '85 Troy Circle', 'Amazonas', 'Centro');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (85, '5674 Lighthouse Bay Park', 'Sergipe.', 'Jardim Paulista');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (86, '9 Stuart Hill', 'Paraná', 'Jardim Europa');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (87, '57001 Dahle Crossing', 'Pará', 'Santa Cecília');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (88, '79 Randy Drive', 'Rio Grande do Sul', 'Tijuca');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (89, '3736 Derek Way', 'Goiás', 'Caminho das Árvores');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (90, '79232 Redwing Point', 'Roraima', 'Jardim Guanabara.');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (91, '7326 South Junction', 'Rio de Janeiro', 'Centro');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (92, '6 Southridge Trail', 'Goiás', 'Farol');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (93, '544 Kennedy Drive', 'Distrito Federal', 'Laranjeiras');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (94, '87483 Boyd Lane', 'Mato Grosso do Sul', 'Tijuca');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (95, '5352 Dakota Hill', 'Piauí', 'Jardins');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (96, '98 Golf Course Center', 'Rio de Janeiro', 'Graça');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (97, '0959 Heath Crossing', 'Rio de Janeiro', 'Morumbi');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (98, '19 Northport Park', 'Bahia', 'Itaim Bibi');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (99, '778 Sunnyside Crossing', 'São Paulo', 'Praia do Canto');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (100, '8505 Saint Paul Trail', 'Rio de Janeiro', 'Flamengo');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (101, '085 Orin Pass', 'Sergipe.', 'Savassi');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (102, '0 Transport Alley', 'Maranhão', 'Graça');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (103, '0843 Golf Course Junction', 'Santa Catarina', 'Farol');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (104, '16 Monica Center', 'Goiás', 'Morumbi');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (105, '05733 Sommers Crossing', 'Piauí', 'Consolação');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (106, '0 Prairieview Lane', 'Mato Grosso', 'Leblon');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (107, '242 Aberg Lane', 'Pará', 'Jardim América');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (108, '77 Novick Avenue', 'Amazonas', 'Boqueirão');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (109, '36 Canary Park', 'Pará', 'Perdizes');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (110, '0252 Magdeline Trail', 'Maranhão', 'Jardins');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (111, '3 Anzinger Way', 'Ceará', 'Boqueirão');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (112, '71 Continental Road', 'Bahia', 'Ipanema');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (113, '5 Buhler Hill', 'Ceará', 'Tijuca');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (114, '17670 Nevada Junction', 'Acre', 'Leblon');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (115, '983 Northland Drive', 'Rio Grande do Sul', 'Centro');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (116, '34 Packers Crossing', 'Minas Gerais', 'São Cristóvão');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (117, '24 Carioca Point', 'Amazonas', 'Lapa');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (118, '546 Hermina Road', 'Pernambuco', 'Petrópolis');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (119, '055 Caliangt Street', 'Pará', 'Jardim América');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (120, '7221 Russell Circle', 'Paraíba', 'Pituba');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (121, '9888 Lillian Avenue', 'Distrito Federal', 'Jardim Paulista');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (122, '3 Myrtle Way', 'São Paulo', 'Moema');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (123, '7680 Dixon Lane', 'São Paulo', 'São Cristóvão');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (124, '42 Commercial Trail', 'São Paulo', 'Perdizes');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (125, '345 Sunbrook Junction', 'Ceará', 'Vila Madalena');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (126, '595 Village Center', 'Sergipe.', 'Laranjeiras');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (127, '127 Dwight Hill', 'Roraima', 'Graça');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (128, '66 Redwing Junction', 'Mato Grosso do Sul', 'Petrópolis');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (129, '3079 Beilfuss Lane', 'Bahia', 'Moema');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (130, '895 Thompson Court', 'Amapá', 'Moinhos de Vento');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (131, '948 Arrowood Alley', 'Rio de Janeiro', 'São Cristóvão');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (132, '6472 Helena Pass', 'Alagoas', 'Petrópolis');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (133, '53355 Mitchell Parkway', 'Pernambuco', 'Lapa');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (134, '19005 Sunfield Court', 'Amapá', 'Pituba');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (135, '35655 Claremont Street', 'Bahia', 'Cambuí');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (136, '234 Sommers Junction', 'Mato Grosso', 'Boqueirão');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (137, '2 Iowa Center', 'Paraná', 'Cambuí');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (138, '74 Macpherson Road', 'Rio Grande do Norte', 'Jardim Guanabara.');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (139, '772 Gateway Plaza', 'Rio Grande do Sul', 'Laranjeiras');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (140, '88921 Glendale Trail', 'Acre', 'São Cristóvão');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (141, '911 Lerdahl Parkway', 'Mato Grosso', 'Pinheiros');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (142, '19494 Pearson Center', 'Acre', 'Jardins');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (143, '48 Lighthouse Bay Circle', 'Maranhão', 'Jardim Botânico');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (144, '416 Burrows Road', 'Rio Grande do Sul', 'Lapa');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (145, '5271 Northview Alley', 'Ceará', 'Barra Funda');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (146, '94736 Gina Court', 'Rio de Janeiro', 'Moema');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (147, '5817 Ridgeview Alley', 'Paraná', 'Itaim Bibi');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (148, '51 Eastlawn Park', 'Santa Catarina', 'Vila Madalena');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (149, '88 Forster Crossing', 'Ceará', 'Farol');
insert into Tb_Loja (idLoja, Endereco, Estado, Bairro) values (150, '7494 Namekagon Pass', 'Mato Grosso', 'Bela Vista');
